services:
 dwf_pronosticsbundle.type.entity_hidden:
  class: Dwf\PronosticsBundle\Form\Type\EntityHiddenType
  arguments: ["@doctrine.orm.entity_manager"]
  tags:
   - { name: form.type, alias: entity_hidden }
 dwf_pronosticbundle.result:
        class: Dwf\PronosticsBundle\Result\Result
        arguments: [ @doctrine.orm.entity_manager ]
 dwf_pronosticbundle.user_mailer:
        class: Dwf\PronosticsBundle\Mailer\UserMailer
        arguments: 
            0: '@mailer' 
            1: '@router'
            2: '@templating'
            3: 
                confirmation.template: %fos_user.registration.confirmation.template%
                resetting_password.template: %fos_user.resetting.email.template%
                from_email:
                    confirmation: %fos_user.registration.confirmation.from_email%
                    resetting_password: %fos_user.resetting.email.from_email%
 
 dwf_pronosticbundle.type.registration_form:
        class: Dwf\PronosticsBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
         - { name: "form.type", alias: "dwf_pronosticsbundle_user_registration" }
 dwf_pronosticsbunble.registration_listener:
        class: Dwf\PronosticsBundle\EventListener\RegistrationListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }
 dwf_pronosticbundle.invitation.form.type:
        class: Dwf\PronosticsBundle\Form\Type\InvitationFormType
        arguments: [@dwf_pronosticbundle.invitation.form.data_transformer]
        tags:
         - { name: "form.type", alias: "dwf_pronosticsbundle_invitation_type" }

 dwf_pronosticbundle.invitation.form.data_transformer:
        class: Dwf\PronosticsBundle\Form\DataTransformer\InvitationToCodeTransformer
        arguments: [@doctrine.orm.entity_manager]
 dwf_pronosticbundle.championshipmanager:
        class: Dwf\PronosticsBundle\Championship\ChampionshipManager
        arguments: [ @doctrine.orm.entity_manager ]
 dwf_pronosticbundle.highchartmanager:
        class: Dwf\PronosticsBundle\Championship\HighchartManager
        arguments: []