dwf_pronostics:
    resource: "@DwfPronosticsBundle/Controller/"
    type:     annotation
    prefix:   /

dwf_page:
    resource: "@DwfPageBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
