services:
    sonata.admin.page:
        class: Dwf\PageBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Page" }
        arguments:
            - ~
            - Dwf\PageBundle\Entity\Page
            - DwfPageBundle:CRUD
            