parameters:
#    dwf_page.example.class: Dwf\PageBundle\Example

services:
#    dwf_page.example:
#        class: %dwf_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
